-- 1. TABEL USERS (Admin & Guru)
CREATE TABLE `USERS` (
    `ID` INT(11) NOT NULL AUTO_INCREMENT,
    `USERNAME` VARCHAR(50) NOT NULL,
    `PASSWORD` VARCHAR(255) NOT NULL,
    `NAMA_LENGKAP` VARCHAR(100) NOT NULL,
    `JENIS_KELAMIN` ENUM('L', 'P') DEFAULT 'L',
    `NIP` VARCHAR(30) DEFAULT NULL,
    `TEMPAT_LAHIR` VARCHAR(50) DEFAULT NULL,
    `TANGGAL_LAHIR` DATE DEFAULT NULL,
    `ALAMAT` TEXT DEFAULT NULL,
    `NO_TELEPON` VARCHAR(15) DEFAULT NULL,
    `EMAIL` VARCHAR(100) DEFAULT NULL,
    `ROLE` ENUM('admin', 'guru') DEFAULT 'guru',
    `JABATAN` VARCHAR(100) DEFAULT NULL,
    `BIDANG_STUDI` VARCHAR(100) DEFAULT NULL,
    `FOTO` VARCHAR(255) DEFAULT NULL,
    `STATUS` ENUM('aktif', 'nonaktif', 'pensiun', 'pindah') DEFAULT 'aktif',
    `LAST_LOGIN` TIMESTAMP NULL DEFAULT NULL,
    `CREATED_AT` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `UPDATED_AT` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`ID`),
    UNIQUE KEY `IDX_USERS_USERNAME` (`USERNAME`),
    UNIQUE KEY `IDX_USERS_NIP` (`NIP`),
    UNIQUE KEY `IDX_USERS_EMAIL` (`EMAIL`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8MB4;

-- 2. TABEL TAHUN AJARAN
CREATE TABLE `TAHUN_AJARAN` (
    `ID` INT(11) NOT NULL AUTO_INCREMENT,
    `TAHUN_AJARAN` VARCHAR(9) NOT NULL,
    `TANGGAL_MULAI` DATE NOT NULL,
    `TANGGAL_SELESAI` DATE NOT NULL,
    `STATUS` ENUM('aktif', 'selesai', 'akan_datang') DEFAULT 'akan_datang',
    `CREATED_AT` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `UPDATED_AT` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`ID`),
    UNIQUE KEY `IDX_TA_UNIQUE` (`TAHUN_AJARAN`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8MB4;

-- 3. TABEL SEMESTER
CREATE TABLE `SEMESTER` (
    `ID` INT(11) NOT NULL AUTO_INCREMENT,
    `TAHUN_AJARAN` VARCHAR(9) NOT NULL,
    `SEMESTER` ENUM('ganjil', 'genap') NOT NULL,
    `TANGGAL_MULAI` DATE NOT NULL,
    `TANGGAL_SELESAI` DATE NOT NULL,
    `STATUS` ENUM('aktif', 'selesai', 'akan_datang') DEFAULT 'akan_datang',
    `CREATED_AT` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `UPDATED_AT` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`ID`),
    UNIQUE KEY `UNIQUE_SEMESTER` (`TAHUN_AJARAN`, `SEMESTER`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8MB4;

-- 4. TABEL KELAS
CREATE TABLE `KELAS` (
    `ID` INT(11) NOT NULL AUTO_INCREMENT,
    `KODE_KELAS` VARCHAR(10) NOT NULL,
    `NAMA_KELAS` VARCHAR(50) NOT NULL,
    `TINGKAT` ENUM('X', 'XI', 'XII') NOT NULL,
    `JURUSAN` VARCHAR(50) DEFAULT NULL,
    `WALI_KELAS_ID` INT(11) DEFAULT NULL,
    `KAPASITAS` INT(11) DEFAULT 30,
    `RUANGAN` VARCHAR(20) DEFAULT NULL,
    `TAHUN_AJARAN` VARCHAR(9) DEFAULT NULL,
    `SEMESTER` ENUM('ganjil', 'genap') DEFAULT 'ganjil',
    `STATUS` ENUM('aktif', 'nonaktif') DEFAULT 'aktif',
    `CREATED_AT` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `UPDATED_AT` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`ID`),
    UNIQUE KEY `IDX_KELAS_KODE` (`KODE_KELAS`),
    CONSTRAINT `FK_KELAS_WALI` FOREIGN KEY (`WALI_KELAS_ID`) REFERENCES `USERS` (`ID`) ON DELETE SET NULL
) ENGINE=INNODB DEFAULT CHARSET=UTF8MB4;

-- 5. TABEL SISWA
CREATE TABLE `SISWA` (
    `ID` INT(11) NOT NULL AUTO_INCREMENT,
    `NIS` VARCHAR(20) NOT NULL,
    `NISN` VARCHAR(20) NOT NULL,
    `NAMA_LENGKAP` VARCHAR(100) NOT NULL,
    `JENIS_KELAMIN` ENUM('L', 'P') NOT NULL,
    `TEMPAT_LAHIR` VARCHAR(50) DEFAULT NULL,
    `TANGGAL_LAHIR` DATE DEFAULT NULL,
    `AGAMA` VARCHAR(20) DEFAULT NULL,
    `ALAMAT` TEXT DEFAULT NULL,
    `NO_TELEPON` VARCHAR(15) DEFAULT NULL,
    `EMAIL` VARCHAR(100) DEFAULT NULL,
    `NAMA_AYAH` VARCHAR(100) DEFAULT NULL,
    `NAMA_IBU` VARCHAR(100) DEFAULT NULL,
    `PEKERJAAN_AYAH` VARCHAR(100) DEFAULT NULL,
    `PEKERJAAN_IBU` VARCHAR(100) DEFAULT NULL,
    `NO_TELEPON_ORTU` VARCHAR(15) DEFAULT NULL,
    `KELAS_ID` INT(11) DEFAULT NULL,
    `FOTO` VARCHAR(255) DEFAULT NULL,
    `STATUS` ENUM('aktif', 'alumni', 'pindah', 'keluar', 'dropout') DEFAULT 'aktif',
    `TOTAL_POIN_PRESTASI` INT(11) DEFAULT 0,
    `TOTAL_POIN_PELANGGARAN` INT(11) DEFAULT 0,
    `CREATED_AT` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `UPDATED_AT` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`ID`),
    UNIQUE KEY `IDX_SISWA_NIS` (`NIS`),
    CONSTRAINT `FK_SISWA_KELAS` FOREIGN KEY (`KELAS_ID`) REFERENCES `KELAS` (`ID`) ON DELETE SET NULL
) ENGINE=INNODB DEFAULT CHARSET=UTF8MB4;

-- 6. TABEL MATA PELAJARAN
CREATE TABLE `MATA_PELAJARAN` (
    `ID` INT(11) NOT NULL AUTO_INCREMENT,
    `KODE_MAPEL` VARCHAR(10) NOT NULL,
    `NAMA_MAPEL` VARCHAR(100) NOT NULL,
    `KATEGORI` ENUM('umum', 'jurusan', 'peminatan', 'ekstrakurikuler') DEFAULT 'umum',
    `TINGKAT` ENUM('X', 'XI', 'XII', 'semua') DEFAULT 'semua',
    `JURUSAN` VARCHAR(50) DEFAULT NULL,
    `GURU_ID` INT(11) DEFAULT NULL,
    `KELAS_ID` INT(11) DEFAULT NULL,
    `SEMESTER` ENUM('ganjil', 'genap', 'tahunan') DEFAULT 'tahunan',
    `TAHUN_AJARAN` VARCHAR(9) DEFAULT NULL,
    `JAM_PER_MINGGU` INT(11) DEFAULT 2,
    `STATUS` ENUM('aktif', 'nonaktif') DEFAULT 'aktif',
    `CREATED_AT` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `UPDATED_AT` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`ID`),
    UNIQUE KEY `IDX_MAPEL_KODE` (`KODE_MAPEL`),
    CONSTRAINT `FK_MAPEL_GURU` FOREIGN KEY (`GURU_ID`) REFERENCES `USERS` (`ID`) ON DELETE SET NULL,
    CONSTRAINT `FK_MAPEL_KELAS` FOREIGN KEY (`KELAS_ID`) REFERENCES `KELAS` (`ID`) ON DELETE CASCADE
) ENGINE=INNODB DEFAULT CHARSET=UTF8MB4;

-- 7. TABEL JAM PELAJARAN
CREATE TABLE `JAM_PELAJARAN` (
    `ID` INT(11) NOT NULL AUTO_INCREMENT,
    `SESI` INT(11) NOT NULL,
    `JAM_MULAI` TIME NOT NULL,
    `JAM_SELESAI` TIME NOT NULL,
    `KETERANGAN` VARCHAR(50) DEFAULT NULL,
    `JENIS` ENUM('normal', 'istirahat', 'upacara', 'khusus') DEFAULT 'normal',
    `HARI` ENUM('senin', 'selasa', 'rabu', 'kamis', 'jumat', 'sabtu', 'minggu', 'semua') DEFAULT 'semua',
    `STATUS` ENUM('aktif', 'nonaktif') DEFAULT 'aktif',
    `CREATED_AT` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `UPDATED_AT` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8MB4;

-- 8. TABEL JADWAL KELAS
CREATE TABLE `JADWAL_KELAS` (
    `ID` INT(11) NOT NULL AUTO_INCREMENT,
    `HARI` ENUM('Senin', 'Selasa', 'Rabu', 'Kamis', 'Jumat', 'Sabtu') NOT NULL,
    `SESI` INT(11) NOT NULL,
    `MAPEL_ID` INT(11) DEFAULT NULL,
    `KELAS_ID` INT(11) DEFAULT NULL,
    `GURU_ID` INT(11) DEFAULT NULL,
    `RUANGAN` VARCHAR(20) DEFAULT NULL,
    `TAHUN_AJARAN` VARCHAR(9) DEFAULT NULL,
    `SEMESTER` ENUM('ganjil', 'genap') DEFAULT 'ganjil',
    `STATUS` ENUM('aktif', 'nonaktif') DEFAULT 'aktif',
    `CREATED_AT` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `UPDATED_AT` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`ID`),
    UNIQUE KEY `UNIQUE_JADWAL` (`HARI`, `SESI`, `KELAS_ID`, `TAHUN_AJARAN`, `SEMESTER`),
    CONSTRAINT `FK_JADWAL_MAPEL` FOREIGN KEY (`MAPEL_ID`) REFERENCES `MATA_PELAJARAN` (`ID`) ON DELETE CASCADE,
    CONSTRAINT `FK_JADWAL_KELAS` FOREIGN KEY (`KELAS_ID`) REFERENCES `KELAS` (`ID`) ON DELETE CASCADE
) ENGINE=INNODB DEFAULT CHARSET=UTF8MB4;